version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: smartorder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Divij@123
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartorder
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Divij@123
      SPRING_DATA_REDIS_HOST: redis